export const BANKS = [
  { value: 'Akbank', label: 'Akbank' },
  { value: 'Albaraka Türk', label: 'Albaraka Türk' },
  { value: 'Alternatif Bank', label: 'Alternatif Bank' },
  { value: 'Anadolubank', label: 'Anadolubank' },
  { value: 'Burgan Bank', label: 'Burgan Bank' },
  { value: 'DenizBank', label: 'DenizBank' },
  { value: 'Emlak Katılım', label: 'Emlak Katılım' },
  { value: 'Enpara.com', label: 'Enpara.com' },
  { value: 'Fibabanka', label: 'Fibabanka' },
  { value: 'Garanti BBVA', label: 'Garanti BBVA' },
  { value: 'Halkbank', label: 'Halkbank' },
  { value: 'ING', label: 'ING' },
  { value: 'Kuveyt Türk', label: 'Kuveyt Türk' },
  { value: 'Odeabank', label: 'Odeabank' },
  { value: 'QNB', label: 'QNB (Finansbank)' },
  { value: 'Şekerbank', label: 'Şekerbank' },
  { value: 'TEB', label: 'TEB (Türk Ekonomi Bankası)' },
  { value: 'Türkiye Finans', label: 'Türkiye Finans' },
  { value: 'Türkiye İş Bankası', label: 'Türkiye İş Bankası' },
  { value: 'VakıfBank', label: 'VakıfBank' },
  { value: 'Vakıf Katılım', label: 'Vakıf Katılım' },
  { value: 'Yapı Kredi', label: 'Yapı Kredi' },
  { value: 'Ziraat Bankası', label: 'Ziraat Bankası' },
  { value: 'Ziraat Katılım', label: 'Ziraat Katılım' },
  { value: 'Diğer', label: 'Diğer...' },
];

export const ACCOUNT_TYPES = [
  { value: 'Vadesiz', label: 'Vadesiz Hesap' },
  { value: 'Taksitli Kredi', label: 'Taksitli Kredi' },
  { value: 'KMH', label: 'KMH (Ek Hesap)' },
  { value: 'Kredi Kartı', label: 'Kredi Kartı' },
];
